[package]
name = "to-expr-example-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
to-expr-core = { path = "../core" }
to-expr-example-lib = { path = "../example_lib" }

proc-macro2 = "1.0.76"
quote = "1.0.35"
